#!/bin/bash

rm -rf cache/*
grep taskDefinition ~/.run/log/diego-cc-bridge/stager/stager.stdout.log | \
     tail -1 | \
     jq .data.taskDefinition | \
     docker run --rm --user vcap -i -v $PWD/cache:/cache --net hcf stager /stager cache
