#!/usr/bin/ruby

require 'json'
require 'shellwords'

lrp = JSON.parse(STDIN.read)

run = lrp['action']['codependent']['actions'][0]['run']

app_name = "app"
args = []
run['env'].each do |e|
  args += ["-e", "#{e['name']}=#{e['value']}"]
  next unless e['name'] == "VCAP_APPLICATION"
  vcap_app = JSON.parse(e['value'])
  app_name = vcap_app['application_name']
end

image = "#{app_name}:latest"
# Prefix image with registry, if present
image = "#{ARGV[0]}/#{image}" if ARGV.count > 0

# lrp['ports'].each { |p| args += ["-p", "#{p}:#{p}"] }
args += ["-p", "8080:8080"]

puts Shellwords.shelljoin(["run", "--label", "app", "-d", *args, "--user", "vcap",
                           "--name", app_name, image, run['path'], *run['args']])
